import Foundation

/// First half of the outing library: home, outdoors, city, culture.
/// Split across two files and several small arrays purely to keep the Swift
/// type-checker fast — one 140-element literal takes minutes to compile.
enum POLibraryA {

    static var all: [POIdea] {
        home + outdoors + city + culture
    }

    // MARK: - Home

    static var home: [POIdea] {
        [
            POMake("home-shelf-tea",
                   "Reorganize one shelf, then sit with tea",
                   "One shelf. Not the room, not the cupboard, not a system. Take everything off, wipe it, put back only what you want to look at. Then make a hot drink and sit where you can see your work.",
                   .free, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Choose the shelf before you start, out loud",
                    "Clear a patch of floor to stage things on",
                    "Have a bag ready for whatever leaves",
                    "Put the kettle on for the ending"]),

            POMake("home-record-side",
                   "Play one album, whole, sitting down",
                   "No shuffle, no second screen, no tidying while it plays. Pick a record you know is good and give it your entire attention from the first track to the last, the way people used to have to.",
                   .free, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Pick the album before you sit, not during",
                    "Phone in a different room, face down",
                    "Something to drink within reach"]),

            POMake("home-bath-book",
                   "Run a bath so hot the book warps a little",
                   "A proper long soak with a paperback you do not mind damaging. Top the hot water up twice. Come out pink and useless in the good way.",
                   .low, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["A paperback, not a device",
                    "Towel on the floor for wet hands",
                    "Something cold to drink beside the bath"]),

            POMake("home-kitchen-disco",
                   "Cook something slow with the music loud",
                   "Choose a recipe with a long simmer and no rush. The point is the two hours in a warm kitchen with something you like playing, not the eating, though the eating is good too.",
                   .low, .halfDay, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Pick the recipe the day before",
                    "Shop for everything in one trip",
                    "Queue a playlist long enough to outlast the cooking",
                    "Wash up as you go so the ending is clean"]),

            POMake("home-letter-past",
                   "Write a letter to yourself, one year out",
                   "Paper, envelope, the whole ceremony. Tell next year what this year has been like. Seal it, write the date on the front, and put it somewhere you will find it by accident.",
                   .free, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Find paper and an envelope in advance",
                    "Decide where the envelope will live",
                    "Write the open-by date on the front"]),

            POMake("home-window-hour",
                   "Sit at the window for an hour and just watch",
                   "No book, no phone, no purpose. Take the good chair to the window and watch the street or the trees or the weather do whatever it does. Boredom passes at about the twenty-minute mark and something better arrives.",
                   .free, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Move a comfortable chair to the window",
                    "Set a timer so you are not clock-watching",
                    "Phone in another room"]),

            POMake("home-photo-cull",
                   "Cull two thousand photos down to forty",
                   "Start at the oldest end of the camera roll and be brutal. Forty keepers, everything else gone. You will find pictures you forgot you took, which is the actual reward.",
                   .free, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Charge the phone or laptop first",
                    "Decide the keep-number before you begin",
                    "Back up anything precious before deleting"]),

            POMake("home-tasting-flight",
                   "Set up a tasting flight of one thing",
                   "Three teas, three olive oils, three chocolates, three hot sauces — whatever you can buy small. Line them up, taste in order, write one honest sentence about each. You now have an opinion.",
                   .low, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Buy three of the same category, different makers",
                    "Small glasses or plates, numbered",
                    "Paper and pen for the honest sentence",
                    "Plain crackers or water to reset between"]),

            POMake("home-map-wall",
                   "Learn one country properly from an atlas",
                   "Pick somewhere you could not draw from memory. Spend the evening with a map and whatever you can read about it — rivers, borders, why the capital ended up there. Curiosity with no exam at the end.",
                   .free, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Choose the country by closing your eyes",
                    "Find a map big enough to see rivers on",
                    "Keep a list of three things that surprised you"]),

            POMake("home-blanket-double",
                   "Watch two films by the same director back to back",
                   "A double bill, chosen on purpose, with an intermission you actually take. Watching two by one person in one evening shows you the seams — the shot they always use, the ending they always want.",
                   .low, .fullDay, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Pick the director, then the two films",
                    "Make the intermission snack in advance",
                    "Write down the thing both films share"]),

            POMake("home-plant-repot",
                   "Repot everything green you own",
                   "Fresh compost, bigger pots, a trim of the dead bits. Slightly messy, deeply satisfying, and the flat looks different afterwards for about a month.",
                   .low, .couple, .active, .home, .spring, .indoorSafe, .solitary,
                   ["Buy compost and one size up in pots",
                    "Spread newspaper or work outside",
                    "Water everything an hour before you start"]),

            POMake("home-radio-abroad",
                   "Tune into a radio station from a city you have never been to",
                   "Pick a place at random and find its local station online. Sit with the adverts, the traffic report, the strange local pop. It is the cheapest travel there is.",
                   .free, .half, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Choose the city before you look at any stations",
                    "Let it run for at least half an hour",
                    "Note one thing you learned about the place"]),

            POMake("home-inbox-zero-ritual",
                   "Clear every backlog on your desk, then light a candle",
                   "The admin evening, done deliberately rather than resentfully. Bills, forms, the drawer of unopened envelopes. Then a candle and a sit-down, because the ritual is what makes it an outing and not a chore.",
                   .free, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Gather every piece of paper into one pile first",
                    "Have a bin bag and a recycling bag ready",
                    "Buy or find the candle before you start"]),

            POMake("home-old-hobby",
                   "Dig out the hobby you abandoned and give it one evening",
                   "The guitar, the sketchbook, the half-finished model, the chess set. No commitment to resuming it. One evening, no guilt, and if it is still boring you can let it go for good with a clear conscience.",
                   .free, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Find the thing and put it somewhere visible",
                    "Give yourself permission to quit at the end",
                    "Set a modest, finishable first step"]),

            POMake("home-floor-picnic",
                   "Eat dinner on the floor by candlelight",
                   "Blanket down, lights off, candles on, a plate of things you like eating with your hands. The furniture is not compulsory and the room feels borrowed for an evening.",
                   .low, .couple, .restful, .home, .any, .indoorSafe, .solitary,
                   ["Blanket and cushions from the bed",
                    "Food that works cold and by hand",
                    "Three candles, at least, and matches"]),

            POMake("home-language-hour",
                   "Spend an hour on a language you will never need",
                   "Not for a trip, not for a job. Learn to count to twenty and say something rude in Finnish or Georgian or Welsh. Useless knowledge is the most durable kind.",
                   .free, .couple, .gentle, .home, .any, .indoorSafe, .solitary,
                   ["Pick a language with an alphabet you like",
                    "Find one free lesson or video in advance",
                    "Say everything out loud, badly"]),

            POMake("home-jigsaw-night",
                   "Start a jigsaw and finish the edge",
                   "Table cleared, a thousand pieces out, edges first. Something on in the background that you do not have to look at. Leave it out — an unfinished jigsaw is an open invitation for the rest of the week.",
                   .low, .couple, .restful, .home, .winter, .indoorSafe, .solitary,
                   ["Clear a table you can leave occupied for days",
                    "Sort edge pieces into a lid before starting",
                    "Good light over the table"]),

            POMake("home-sleep-early",
                   "Go to bed at half past eight on purpose",
                   "Clean sheets, curtains closed, no screen after eight. Not because you are ill, not because you have an early start — just because eleven hours of sleep is a luxury and it costs nothing.",
                   .free, .couple, .restful, .home, .winter, .indoorSafe, .solitary,
                   ["Change the sheets that morning",
                    "Put the phone charger out of arm's reach",
                    "Eat earlier than usual"]),

            POMake("home-recipe-family",
                   "Cook the dish someone in your family used to make",
                   "Reconstruct it from memory or ask for the method. It will not be quite right the first time. That is fine — the kitchen smelling like that again is the entire point.",
                   .low, .couple, .gentle, .home, .any, .indoorSafe, .talking,
                   ["Ask someone for the method a few days before",
                    "Buy the odd ingredient in advance",
                    "Write the recipe down properly as you go"]),

            POMake("home-desk-rearrange",
                   "Move the furniture so the room faces a different way",
                   "The sofa on the other wall, the desk facing the window, the bed rotated. An afternoon of shoving things around and you get to live somewhere new without moving.",
                   .free, .halfDay, .active, .home, .any, .indoorSafe, .solitary,
                   ["Measure the awkward piece before you commit",
                    "Clear the floor along the route",
                    "Hoover the patches nothing has stood on for years"]),
        ]
    }

    // MARK: - Outdoors

    static var outdoors: [POIdea] {
        [
            POMake("out-last-stop",
                   "Take the bus to the last stop and walk back",
                   "Get on, stay on past where you would normally get off, and get out where the route ends. Then walk home, or as far as your legs like. You will see the edge of your own city, which most people never do.",
                   .low, .halfDay, .active, .outdoors, .any, .needsDry, .strangers,
                   ["Check the last return service before you go",
                    "Comfortable shoes, not the nice ones",
                    "Water and something to eat in a pocket",
                    "Charge your phone for the map home"]),

            POMake("out-dawn-walk",
                   "Be outside before the sun comes up",
                   "Set an alarm you will resent, get out into the blue dark, and be somewhere with a view when it turns. The city belongs to about nine people at that hour and you will be one of them.",
                   .free, .couple, .gentle, .outdoors, .any, .needsDry, .solitary,
                   ["Look up the sunrise time and subtract forty minutes",
                    "Lay clothes out the night before",
                    "Pick the viewing spot in advance",
                    "Take a flask"]),

            POMake("out-hill-nothing",
                   "Climb the nearest hill and do nothing at the top",
                   "Up is the easy part to plan. The discipline is sitting at the top for a full half hour without taking a photograph, checking anything, or turning straight round.",
                   .free, .halfDay, .active, .outdoors, .any, .needsDry, .solitary,
                   ["Find the route and the parking or bus stop",
                    "Layers — the top is always colder",
                    "Take a sandwich to earn the sitting"]),

            POMake("out-tree-sit",
                   "Find one tree and sit under it until you can describe it",
                   "Pick a good big one in a park. Sit against it long enough to notice the bark, the sound it makes, what lives on it. You will come away able to find that exact tree again for the rest of your life.",
                   .free, .couple, .restful, .outdoors, .any, .needsDry, .solitary,
                   ["Something waterproof to sit on",
                    "Notebook, if you like writing things down",
                    "No timer — leave when you are ready"]),

            POMake("out-night-sky",
                   "Get far enough out of town to see actual stars",
                   "Drive or take a train until the orange glow stops. Lie on your back on something dry and give your eyes twenty full minutes to adjust before you decide whether it was worth it.",
                   .low, .halfDay, .adventurous, .outdoors, .any, .needsCold, .solitary,
                   ["Check the moon phase — a full moon ruins it",
                    "Blanket, foam mat, and a warm coat",
                    "Red light or a torch with tape over it",
                    "Tell someone roughly where you are going"]),

            POMake("out-graveyard-walk",
                   "Walk a very old cemetery slowly and read the stones",
                   "They are the quietest parks in any city and full of extraordinary sentences. Read the dates, do the arithmetic, notice which decades were bad ones. Oddly cheering rather than grim.",
                   .free, .couple, .restful, .outdoors, .autumn, .needsDry, .solitary,
                   ["Find the opening hours — many close at dusk",
                    "Wear shoes for uneven ground",
                    "Note the oldest date you can find"]),

            POMake("out-forage-walk",
                   "Learn to identify three plants on one walk",
                   "Take a guide or an offline identification app and commit to three, properly — leaf, smell, where it grows. Three is enough to change how a hedgerow looks forever.",
                   .free, .couple, .gentle, .outdoors, .spring, .needsDry, .solitary,
                   ["Download an offline plant guide",
                    "Do not eat anything you identified today",
                    "Photograph each one for later checking"]),

            POMake("out-rain-walk",
                   "Go for a walk specifically because it is raining",
                   "Proper coat, no umbrella, no destination. Everyone else is inside, the streets sound different, and coming home to dry clothes afterwards is one of the great small pleasures.",
                   .free, .couple, .gentle, .outdoors, .autumn, .indoorSafe, .solitary,
                   ["Waterproof coat and shoes you can dry",
                    "Phone in a bag or a pocket that seals",
                    "Have dry clothes and a hot drink waiting"]),

            POMake("out-picnic-solo",
                   "Take a properly good picnic somewhere and eat it alone",
                   "Not sad sandwiches. The nice bread, the good cheese, one thing you would never normally buy. Spread a blanket in a park and take an hour over it.",
                   .low, .couple, .restful, .outdoors, .summer, .needsSun, .strangers,
                   ["Shop the day before, not on the way",
                    "Blanket, knife, napkin, something to drink",
                    "Scout a spot with shade and a view",
                    "Bag for taking the rubbish home"]),

            POMake("out-orienteer",
                   "Navigate somewhere new with a paper map only",
                   "Print or buy a map, put the phone away, and get yourself across town or across a park the old way. Getting mildly lost is part of the deal and the whole reason it works.",
                   .low, .halfDay, .adventurous, .outdoors, .any, .needsDry, .solitary,
                   ["Print or buy the map the day before",
                    "Keep the phone charged but pocketed",
                    "Choose an obvious, findable end point"]),

            POMake("out-bench-tour",
                   "Sit on five different benches in one afternoon",
                   "A silly premise that works beautifully. Walk between five benches you have never sat on, spend ten minutes on each, and notice how differently the same city reads from each one.",
                   .free, .halfDay, .gentle, .outdoors, .any, .needsDry, .strangers,
                   ["Pick the first bench, improvise the rest",
                    "Ten minutes minimum on each, no cheating",
                    "Something to read for the dull ones"]),

            POMake("out-snow-first",
                   "Be the first person to walk on fresh snow",
                   "It requires getting up early and it lasts about twenty minutes a year. Untouched snow with your footprints as the only ones is worth setting an alarm for.",
                   .free, .half, .gentle, .outdoors, .winter, .needsCold, .solitary,
                   ["Boots and gloves by the door the night before",
                    "Pick a park or square likely to be empty",
                    "Go before the gritters and the dogs"]),

            POMake("out-blossom-hunt",
                   "Find the best blossom tree in your area and go back three times",
                   "Track one tree through the two weeks it does its thing. Before, during, after. It is a small piece of ongoing business with the world and it costs nothing.",
                   .free, .half, .gentle, .outdoors, .spring, .needsDry, .solitary,
                   ["Pick your tree in the first week of blossom",
                    "Photograph from the same spot each time",
                    "Note the date it drops"]),

            POMake("out-sunset-spot",
                   "Find the best sunset spot within walking distance",
                   "Not the famous one. Yours. Work out which direction west is from your front door and walk that way until something opens up. Then come back on a clear evening and use it.",
                   .free, .couple, .gentle, .outdoors, .summer, .needsSun, .solitary,
                   ["Check which way west is before setting off",
                    "Leave about an hour before sunset",
                    "Take something to sit on"]),

            POMake("out-litter-loop",
                   "Walk your usual loop with a bag and pick up as you go",
                   "Half an hour, one bag, one glove. Unglamorous and improves the exact ground you walk on every day. Nobody needs to see you do it.",
                   .free, .half, .active, .outdoors, .any, .needsDry, .solitary,
                   ["A sturdy bag and one glove or a litter picker",
                    "Know where you will put the full bag",
                    "Leave the broken glass to the professionals"]),

            POMake("out-camp-garden",
                   "Sleep outside — a garden, a balcony, a legal wild spot",
                   "One night under a sky rather than a ceiling. Even six feet from your own back door it resets something. You will sleep badly and be strangely glad about it.",
                   .low, .fullDay, .adventurous, .outdoors, .summer, .needsDry, .solitary,
                   ["Check the forecast the morning of",
                    "Mat, bag, and one more layer than you think",
                    "Torch and a way to get back inside",
                    "Tell someone if it is not your own garden"]),

            POMake("out-birdwatch-hour",
                   "Sit still with binoculars until you have seen six species",
                   "Anywhere with hedges will do. Six is achievable in an hour almost anywhere and the counting is what makes you actually look rather than glance.",
                   .low, .couple, .restful, .outdoors, .any, .needsDry, .solitary,
                   ["Borrow or buy cheap binoculars",
                    "An offline bird guide or chart",
                    "Something warm to sit on and a flask"]),

            POMake("out-park-full-lap",
                   "Walk the entire boundary of the biggest park near you",
                   "Not through it — around the edge, the whole perimeter, no shortcuts. You will find corners and gates you never knew existed after years of crossing the middle.",
                   .free, .halfDay, .active, .outdoors, .any, .needsDry, .strangers,
                   ["Look at the park map and find the perimeter",
                    "Water and comfortable shoes",
                    "Note where the gates are for next time"]),
        ]
    }

    // MARK: - City

    static var city: [POIdea] {
        [
            POMake("city-hotel-lobby",
                   "Read in the lobby of a hotel you are not staying in",
                   "The best free reading rooms in any city have doormen. Walk in like you belong, take the good armchair, order one coffee, and stay two hours. Nobody will ask.",
                   .low, .couple, .restful, .city, .any, .indoorSafe, .strangers,
                   ["Pick a hotel grand enough to have a lobby",
                    "Take an actual book, not a phone",
                    "Order something so you are a customer"]),

            POMake("city-one-street",
                   "Walk one street from end to end and look up",
                   "Choose a long street you only ever cross. Walk the whole thing on one side and back on the other, and keep your eyes above the shopfronts. Every city hides its best architecture on the first floor.",
                   .free, .couple, .gentle, .city, .any, .needsDry, .strangers,
                   ["Pick the street on a map beforehand",
                    "Both sides — the return leg is not optional",
                    "Photograph the three best windows"]),

            POMake("city-library-day",
                   "Spend a whole day in the biggest library you can reach",
                   "Arrive at opening. Take a desk. Read whatever you feel like, in any order, with no goal at all. Libraries are the last indoor place you can sit all day for free without anyone hurrying you.",
                   .free, .fullDay, .restful, .city, .any, .indoorSafe, .strangers,
                   ["Check opening hours and whether you need a card",
                    "Bring a notebook and a water bottle",
                    "Plan where lunch comes from",
                    "Leave the laptop at home if you can bear it"]),

            POMake("city-lost-deliberate",
                   "Get deliberately lost with three coin flips",
                   "At every junction, flip: heads left, tails right, edge means straight on. Forty minutes of that and you will be somewhere you have never stood. Then navigate home properly.",
                   .free, .couple, .adventurous, .city, .any, .needsDry, .strangers,
                   ["A coin, or a random number on your phone",
                    "Charged phone for the journey home",
                    "Set a turn-around time before you start"]),

            POMake("city-market-early",
                   "Get to the market at opening and buy one strange thing",
                   "Early is when the traders are cheerful and the produce is best. Buy one ingredient you cannot identify and ask the person selling it what to do with it. That is the whole outing.",
                   .low, .couple, .gentle, .city, .any, .needsDry, .talking,
                   ["Find the opening time — it is earlier than you think",
                    "Take cash and a bag",
                    "Decide you will ask one question out loud"]),

            POMake("city-tourist-home",
                   "Do the tourist thing in your own city",
                   "The open-top bus, the guided walk, the observation deck. It is deeply undignified and you will learn four things about where you live that you did not know.",
                   .moderate, .halfDay, .gentle, .city, .any, .needsDry, .strangers,
                   ["Book ahead if the good one sells out",
                    "Go on a weekday for smaller crowds",
                    "Layers — open tops are cold"]),

            POMake("city-department-store",
                   "Browse a department store with a strict zero budget",
                   "Try things on, smell the perfumes, sit in the display armchairs, ride every escalator to the top. Buying nothing turns shopping into a museum visit and it is much better that way.",
                   .free, .couple, .gentle, .city, .any, .indoorSafe, .strangers,
                   ["Leave the cards at home if you do not trust yourself",
                    "Start at the top floor and work down",
                    "Find the café on the top floor for the ending"]),

            POMake("city-station-watch",
                   "Sit in a railway station and watch the arrivals",
                   "Buy a coffee, find a seat on the concourse, and watch people meet each other. It is the most consistently moving free show in any city and it runs all day.",
                   .low, .couple, .restful, .city, .any, .indoorSafe, .strangers,
                   ["Find a station with a concourse you can sit in",
                    "Go at a busy arrival time, early evening",
                    "Something to drink so you have a reason to sit"]),

            POMake("city-cinema-afternoon",
                   "See a film on a weekday afternoon with nine other people",
                   "The two o'clock showing on a Tuesday is the best-kept secret in cinema. Almost empty, cheaper, and the walk out into daylight afterwards is disorienting in a lovely way.",
                   .low, .couple, .restful, .city, .any, .indoorSafe, .strangers,
                   ["Check the weekday matinee price",
                    "Pick the film, not the time slot",
                    "Sit dead center because you can"]),

            POMake("city-bookshop-blind",
                   "Buy a book from a shelf you never look at",
                   "Walk to the section you have ignored your entire reading life — poetry, natural history, shipping — and buy the one with the best first page. Then read it somewhere nearby.",
                   .low, .couple, .gentle, .city, .any, .indoorSafe, .strangers,
                   ["Decide the unfamiliar section before you go in",
                    "Read three first pages before choosing",
                    "Find a café for immediately afterwards"]),

            POMake("city-architecture-hunt",
                   "Find the oldest building in your neighborhood",
                   "Look for the date stones, the odd rooflines, the building the street bends around. Then find out what it was. Local history is mostly hiding in plain sight at eye level.",
                   .free, .couple, .gentle, .city, .any, .needsDry, .solitary,
                   ["Look up your area's listed buildings first",
                    "Photograph date stones and plaques",
                    "Somewhere to read about it afterwards"]),

            POMake("city-night-bus",
                   "Ride a night bus across town and back for no reason",
                   "The top deck at midnight, the city smeared and orange, nobody expecting anything of you. Get off where it turns around and get straight back on.",
                   .low, .couple, .adventurous, .city, .any, .indoorSafe, .strangers,
                   ["Check that the return service exists",
                    "Sit upstairs at the front",
                    "Have a way home if the bus stops running",
                    "Tell someone your route"]),

            POMake("city-neighbourhood-swap",
                   "Spend a day in a part of town you never go to",
                   "Cross whichever river, railway or ring road you never cross. Have your coffee there, your lunch there, your afternoon there. Same city, different life.",
                   .low, .fullDay, .gentle, .city, .any, .needsDry, .strangers,
                   ["Pick the neighborhood on a map, not by reputation",
                    "Find one anchor — a café or a park",
                    "Leave the rest of the day unplanned"]),

            POMake("city-record-shop",
                   "Spend an hour in a record or charity shop and buy one thing under a fiver",
                   "Flick through everything. Handle the sleeves. Buy the strangest thing you can afford. Low stakes, high reward, and the assistant has heard worse choices.",
                   .low, .couple, .gentle, .city, .any, .indoorSafe, .strangers,
                   ["Set the spending cap before you go in",
                    "Take cash so the cap is real",
                    "Give it a full hour, not ten minutes"]),

            POMake("city-viewpoint-paid",
                   "Pay for the view from the top of something",
                   "The tower, the cathedral roof, the observation floor. Yes, it is a tourist tax. Yes, seeing the whole shape of where you live laid out below you is worth it once a year.",
                   .moderate, .couple, .gentle, .city, .any, .needsSun, .strangers,
                   ["Book a clear day, not just any day",
                    "Book online — it is usually cheaper",
                    "Go near sunset if the timing allows"]),

            POMake("city-stationery-splurge",
                   "Buy proper stationery and use it that evening",
                   "One good pen, one good notebook, from a shop that cares. Then go straight home and write four pages in it so it never becomes a too-nice-to-use object.",
                   .moderate, .couple, .gentle, .city, .any, .indoorSafe, .strangers,
                   ["Find a real stationery shop, not a supermarket",
                    "Test the pens before you buy",
                    "Commit to using it the same day"]),

            POMake("city-free-tour",
                   "Take a free walking tour and ask one question",
                   "Guides are usually enthusiasts and enthusiasts are good company. Tip properly at the end. The one question is the whole exposure — after that you can go back to listening.",
                   .low, .halfDay, .gentle, .city, .any, .needsDry, .talking,
                   ["Book a place if it needs booking",
                    "Cash for the tip",
                    "Think of your one question in advance",
                    "Comfortable shoes — they walk far"]),

            POMake("city-hotel-night",
                   "Book one night in a hotel in your own city",
                   "Absurd, indulgent, and one of the best things you can do for yourself. Nobody knows where you are, the bed is enormous, and breakfast happens without you.",
                   .splurge, .fullDay, .restful, .city, .any, .indoorSafe, .strangers,
                   ["Book somewhere with a bath and a good breakfast",
                    "Pack absurdly light — one bag",
                    "Take a book and no work",
                    "Check the late checkout option"]),
        ]
    }

    // MARK: - Culture

    static var culture: [POIdea] {
        [
            POMake("cult-one-painting",
                   "Go to a gallery and look at exactly one painting",
                   "Walk past everything else. Find the one, sit down in front of it, and stay for forty minutes. You will see things in the last ten minutes that were invisible in the first ten.",
                   .free, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Check the gallery is free and open",
                    "Choose your painting in the first ten minutes",
                    "Find the bench or bring patience for standing"]),

            POMake("cult-concert-cheap",
                   "Buy the cheapest seat at a classical concert",
                   "The back of the balcony costs less than dinner and the sound up there is often better. Nobody looks at you, everybody is facing the same way, and the interval drink is part of it.",
                   .low, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Book the cheap seat a week ahead",
                    "Read one paragraph about the main piece",
                    "Arrive early enough for the interval drink"]),

            POMake("cult-museum-weird",
                   "Visit the least popular museum in town",
                   "The one about lawnmowers, or plumbing, or one very local industry. Tiny museums are staffed by people who genuinely love the subject and it is contagious within ten minutes.",
                   .low, .couple, .gentle, .culture, .any, .indoorSafe, .talking,
                   ["Find the odd museum and check its hours",
                    "Take cash — small museums often want it",
                    "Ask the person on the desk what to look at"]),

            POMake("cult-play-solo",
                   "See a play alone from the front row",
                   "Front rows are often the cheapest and always the best. Being close enough to see the actors sweat changes theater from a screen into an event happening in your presence.",
                   .moderate, .couple, .gentle, .culture, .any, .indoorSafe, .strangers,
                   ["Look for day seats or front-row deals",
                    "Eat before — intervals are expensive",
                    "Get there early enough to read the program"]),

            POMake("cult-open-mic",
                   "Watch an open mic night from the back",
                   "Poetry, comedy, whatever the venue does. Some of it will be terrible. All of it took nerve. Two hours of people trying is unexpectedly good for the soul.",
                   .low, .couple, .gentle, .culture, .any, .indoorSafe, .strangers,
                   ["Check what night the venue runs it",
                    "Get there early enough for a seat at the back",
                    "Cash for the door and a drink"]),

            POMake("cult-lecture-public",
                   "Sit in on a free public lecture about something you know nothing about",
                   "Universities and museums give them away constantly. Astrophysics, medieval law, urban drainage. Understanding sixty percent of it is a perfectly good result.",
                   .free, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Find the public events page and book a place",
                    "Take a notebook, not a laptop",
                    "Arrive ten minutes early for a good seat"]),

            POMake("cult-sculpture-walk",
                   "Track down every public sculpture within a mile",
                   "Most cities have dozens and most people have walked past them a thousand times. Make a list, find them all, and read the plaques. A treasure hunt you invented.",
                   .free, .halfDay, .active, .culture, .any, .needsDry, .solitary,
                   ["Search your city's public art register",
                    "Plan a walking order so it is a loop",
                    "Photograph each one as proof"]),

            POMake("cult-vinyl-listening",
                   "Go to a listening bar or a record shop with a turntable",
                   "Somewhere that plays whole albums properly through good speakers, where talking loudly is frowned upon. Exactly the right amount of company: present, silent, facing the music.",
                   .moderate, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Find a listening bar or a shop with a booth",
                    "Go early evening before it fills",
                    "Have one drink and stay for a whole side"]),

            POMake("cult-foreign-film",
                   "See a film in a language you do not speak",
                   "Subtitles force you to actually watch. Choose a country whose cinema you know nothing about and go in cold, without reading a single review.",
                   .low, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Pick by country, not by review score",
                    "Check the screening has subtitles",
                    "Read nothing about the plot beforehand"]),

            POMake("cult-archive-visit",
                   "Ask the local archive to show you something",
                   "Local record offices will bring you the actual paper — maps of your street from 1890, records of who lived in your building. You have to ask, which is the whole cost.",
                   .free, .halfDay, .gentle, .culture, .any, .indoorSafe, .talking,
                   ["Email or ring ahead — most need notice",
                    "Bring photo ID, they usually ask",
                    "Have one specific question ready",
                    "Pencil only — archives ban pens"]),

            POMake("cult-cathedral-sit",
                   "Sit in a big old church on a weekday with no service on",
                   "Believer or not, an empty cathedral on a Tuesday morning is one of the few places built specifically to make people quieter. Sit at the back and let the ceiling do its work.",
                   .free, .couple, .restful, .culture, .any, .indoorSafe, .solitary,
                   ["Check visiting hours and any service times",
                    "Coins for the donation box",
                    "Go on a weekday morning if you can"]),

            POMake("cult-poetry-memorise",
                   "Memorize a poem well enough to say it out loud",
                   "Pick something forty lines or under. Two hours of repetition and it is yours forever, retrievable on any train platform for the rest of your life.",
                   .free, .couple, .gentle, .culture, .any, .indoorSafe, .solitary,
                   ["Choose the poem before you start",
                    "Print it out and mark the hard joins",
                    "Say it aloud from the beginning"]),

            POMake("cult-gallery-late",
                   "Go to a gallery late opening when it is nearly empty",
                   "Many open one evening a week until nine. The last hour is almost private — no crowds in front of the good rooms, and the walk home in the dark afterwards feels earned.",
                   .free, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Find which evening the late opening is",
                    "Arrive ninety minutes before closing",
                    "Skip the blockbuster show, do the quiet rooms"]),

            POMake("cult-opera-standing",
                   "Get a standing ticket for the opera",
                   "The cheapest tickets in the building, sometimes released on the day. Three hours on your feet, absurd volume, and the most extravagant thing a small amount of money can buy.",
                   .low, .halfDay, .active, .culture, .any, .indoorSafe, .strangers,
                   ["Find out when day tickets are released",
                    "Read the synopsis — it is not cheating",
                    "Wear shoes you can stand in for hours",
                    "Eat properly beforehand"]),

            POMake("cult-museum-sketch",
                   "Take a sketchbook to a museum and draw badly",
                   "Nobody at a museum minds. Drawing an object forces twenty minutes of real looking, which no amount of walking past ever does. The drawing itself is beside the point.",
                   .low, .couple, .gentle, .culture, .any, .indoorSafe, .strangers,
                   ["Small sketchbook and a pencil, no eraser",
                    "Check whether the museum allows sketching",
                    "Choose three objects, not thirty"]),

            POMake("cult-second-hand-print",
                   "Buy one piece of art you actually like and hang it",
                   "A print, a junk shop watercolor, a poster from an exhibition. Cheap art is still art and a wall you chose beats a wall you inherited.",
                   .moderate, .couple, .gentle, .culture, .any, .indoorSafe, .strangers,
                   ["Measure the wall before you shop",
                    "Take a hook and a hammer home too",
                    "Hang it the same day"]),

            POMake("cult-festival-single",
                   "Buy one day ticket to a festival and go for the day",
                   "One day, one bag, one list of three things you actually want to see. Crowds are excellent cover — nobody at a festival has any idea who came with whom.",
                   .splurge, .fullDay, .adventurous, .culture, .summer, .needsDry, .strangers,
                   ["Book the day ticket and check the timetable",
                    "Three must-see acts, no more",
                    "Water bottle, sun protection, cash",
                    "Plan how you get home afterwards"]),

            POMake("cult-dance-watch",
                   "See dance without knowing anything about dance",
                   "Contemporary, ballet, flamenco — the cheap seat again. Do not try to work out what it means. Watch the bodies do impossible things and let that be enough.",
                   .moderate, .couple, .restful, .culture, .any, .indoorSafe, .strangers,
                   ["Book the cheapest seat with a full view",
                    "Read nothing beforehand",
                    "Note one movement you will remember"]),
        ]
    }
}
