import Foundation

/// Second half of the outing library: water, food, making, moving.
enum POLibraryB {

    static var all: [POIdea] {
        water + food + making + moving
    }

    // MARK: - Water

    static var water: [POIdea] {
        [
            POMake("water-cold-swim",
                   "Swim outdoors in water that is much too cold",
                   "Lake, sea, lido, river with a proper access point. Three minutes is plenty. The hour afterwards, when everything is buzzing and nothing much bothers you, is what you are actually going for.",
                   .free, .couple, .adventurous, .water, .any, .needsCold, .strangers,
                   ["Check it is a recognized swimming spot",
                    "Never alone in open water — go where others swim",
                    "Towel, warm layers and a hot drink for after",
                    "Get out earlier than you think you need to"]),

            POMake("water-lido-lengths",
                   "Swim slow lengths in an outdoor pool",
                   "Not training. Not counting seriously. Just the rhythm of it, the sky above the lane, and forty minutes where nobody can talk to you because your ears are underwater.",
                   .low, .couple, .active, .water, .summer, .needsSun, .strangers,
                   ["Check the lane swimming timetable",
                    "Goggles, and a lock for the locker",
                    "Coins if the lockers need them"]),

            POMake("water-river-walk",
                   "Follow a river or canal until it stops being interesting",
                   "Pick it up wherever you can and walk downstream. Towpaths are flat, well-signed and go through the backs of places you only ever see the fronts of.",
                   .free, .halfDay, .active, .water, .any, .needsDry, .strangers,
                   ["Find an access point and a way back",
                    "Check the towpath is open along your stretch",
                    "Water and a snack — few shops on a towpath"]),

            POMake("water-ferry-cheap",
                   "Take the cheapest ferry available and stand on deck",
                   "River crossing, harbor hopper, the commuter boat. Ten minutes on open water changes a day out of all proportion to what it costs. Stand outside even if it is cold.",
                   .low, .half, .gentle, .water, .any, .needsDry, .strangers,
                   ["Check the timetable and the return crossing",
                    "A warm layer — decks are always colder",
                    "Stand at the rail, not in the cabin"]),

            POMake("water-rockpool",
                   "Spend two hours in rock pools at low tide",
                   "Yes, on your own, at whatever age you are. Rock pools do not care. Crouch down, turn over one rock at a time, and put everything back exactly as you found it.",
                   .free, .couple, .gentle, .water, .summer, .needsDry, .solitary,
                   ["Look up the low tide time",
                    "Shoes with grip that you can get wet",
                    "Watch the tide turn — do not get cut off",
                    "Put every rock back the way it was"]),

            POMake("water-sauna-plunge",
                   "Book a sauna session and use the cold plunge properly",
                   "Three rounds: hot, cold, rest. Silence is the norm in a good sauna, which makes it the rare public place where being alone is the expected behavior.",
                   .moderate, .couple, .restful, .water, .winter, .indoorSafe, .strangers,
                   ["Book the session in advance",
                    "Towel, water bottle, flip-flops",
                    "Drink water between every round",
                    "Do not skip the resting round"]),

            POMake("water-paddle-hire",
                   "Hire a kayak or a paddleboard for an hour",
                   "Sheltered water, an hour, an instructor's five-minute briefing. You will be terrible for ten minutes and then suddenly not, which is the best sequence any activity can offer.",
                   .moderate, .couple, .active, .water, .summer, .needsSun, .talking,
                   ["Book the hire and ask about beginners",
                    "Clothes that can get soaked",
                    "Waterproof bag or leave the phone ashore",
                    "Sun protection — water doubles it"]),

            POMake("water-fountain-sit",
                   "Sit by moving water in the city for an hour",
                   "A fountain, a weir, a canal lock. Moving water is the one piece of free white noise a city gives away, and an hour beside it does more than an hour of anything else.",
                   .free, .couple, .restful, .water, .summer, .needsDry, .strangers,
                   ["Find the fountain or weir on a map",
                    "Something to sit on if there are no benches",
                    "Go at a quiet hour"]),

            POMake("water-harbour-boats",
                   "Walk a harbor and read the names on the boats",
                   "Every boat is named by someone who cared about the name. Walk the pontoons or the quay, read all of them, and pick the one you would have chosen.",
                   .free, .couple, .gentle, .water, .any, .needsDry, .solitary,
                   ["Find a harbor with public access",
                    "Wind-proof layer — harbors are exposed",
                    "Write down the three best names"]),

            POMake("water-hot-springs",
                   "Book somewhere with hot water and stay in it too long",
                   "Thermal baths, a spa afternoon, a hotel pool day pass. Buy the whole afternoon rather than an hour and treat it as the destination, not an add-on.",
                   .splurge, .halfDay, .restful, .water, .winter, .indoorSafe, .strangers,
                   ["Book an afternoon slot, not the minimum",
                    "Swimsuit, towel, flip-flops",
                    "Eat lightly beforehand",
                    "Leave the phone in the locker"]),

            POMake("water-tide-watch",
                   "Watch a tide come in from the same spot for two hours",
                   "Find the tide table, arrive at low water, and stay until the sand you were standing on is gone. Extremely slow, extremely absorbing, entirely free.",
                   .free, .couple, .restful, .water, .autumn, .needsDry, .solitary,
                   ["Look up the tide table for the day",
                    "Choose a safe high spot to end on",
                    "Warm layers and a flask",
                    "Mark the waterline at the start"]),

            POMake("water-boat-trip",
                   "Take a proper boat trip with a commentary",
                   "The two-hour one, with the guide who has said it ten thousand times and still likes the good bits. Sit outside at the back where the engine noise is lowest.",
                   .moderate, .halfDay, .gentle, .water, .summer, .needsSun, .strangers,
                   ["Book the sailing and check the meeting point",
                    "Warm layer even in summer",
                    "Sun protection and water",
                    "Arrive early for an outside seat"]),
        ]
    }

    // MARK: - Food

    static var food: [POIdea] {
        [
            POMake("food-magazine-cafe",
                   "Read a whole magazine cover to cover in a café",
                   "Buy the fat glossy one you would never normally justify. Take a corner table, order something that comes in a proper cup, and read every page including the adverts. Two hours, no scrolling.",
                   .low, .couple, .restful, .food, .any, .indoorSafe, .strangers,
                   ["Buy the magazine before you sit down",
                    "Choose a café with tables you can occupy",
                    "Leave the headphones at home",
                    "Order the thing you actually want"]),

            POMake("food-counter-dinner",
                   "Eat dinner at the bar of a good restaurant",
                   "Counter seats are the best seats and they exist precisely for people arriving alone. You get the kitchen as your view, faster service, and the option of talking or not.",
                   .moderate, .couple, .gentle, .food, .any, .indoorSafe, .strangers,
                   ["Ring ahead and ask if they seat at the counter",
                    "Go early — counters fill first",
                    "Take a book as an option, not a shield"]),

            POMake("food-tasting-menu",
                   "Book the tasting menu somewhere serious",
                   "The full extravagance, on a weekday when it is easier to get in. Nine courses, two hours, and nobody to negotiate the wine with. Restaurants love a solo diner who is paying attention.",
                   .splurge, .halfDay, .gentle, .food, .any, .indoorSafe, .talking,
                   ["Book several weeks out for a good table",
                    "Tell them about any allergies when booking",
                    "Eat lightly during the day",
                    "Decide the budget including service in advance"]),

            POMake("food-breakfast-out",
                   "Have breakfast in a café before work",
                   "An hour earlier than usual, eggs made by someone else, a newspaper. The whole day is subtly better afterwards and it costs less than the equivalent dinner.",
                   .low, .half, .gentle, .food, .any, .indoorSafe, .strangers,
                   ["Find a café that opens early enough",
                    "Set the alarm an hour earlier",
                    "Take a newspaper or a book"]),

            POMake("food-new-cuisine",
                   "Eat a cuisine you have genuinely never tried",
                   "Not a variation on something familiar. Something whose menu you cannot read. Point at two things and ask the server what they would order.",
                   .low, .couple, .adventurous, .food, .any, .indoorSafe, .talking,
                   ["Find the restaurant and check the hours",
                    "Look up two dish names beforehand",
                    "Plan to ask the server for a recommendation",
                    "Go hungry"]),

            POMake("food-bakery-crawl",
                   "Visit three bakeries and rank the same item",
                   "Croissant, cinnamon bun, sourdough loaf — pick one item and buy it in three places in one morning. Eat them side by side. Now you have a favorite bakery, permanently.",
                   .low, .couple, .gentle, .food, .any, .needsDry, .strangers,
                   ["Pick the item and map the three bakeries",
                    "Go in the morning while things are fresh",
                    "Somewhere to sit for the comparison",
                    "Notes on each one while it is fresh"]),

            POMake("food-cook-new",
                   "Cook a dish you have never made before",
                   "Properly new, not a tweak. Read the recipe twice, buy everything, and accept that the first attempt is a draft. Cooking badly for one is a very low-stakes way to learn.",
                   .low, .couple, .gentle, .food, .any, .indoorSafe, .solitary,
                   ["Read the recipe all the way through first",
                    "Shop for everything before you begin",
                    "Clear the counter properly",
                    "Write down what you would change"]),

            POMake("food-picnic-cheese",
                   "Buy the good cheese and eat it at home like a course",
                   "One piece of proper cheese, decent bread, something sharp on the side. Plate it, sit at the table, and treat it as a meal rather than a raid on the fridge.",
                   .moderate, .half, .restful, .food, .any, .indoorSafe, .talking,
                   ["Buy from a counter and ask what is good",
                    "Take it out of the fridge an hour before",
                    "Lay a proper place at the table"]),

            POMake("food-coffee-standards",
                   "Find out what you actually think about coffee",
                   "Order the same drink in three places in one day, or a flight in one place. Decide what you like without anyone else's opinion in the room.",
                   .low, .couple, .gentle, .food, .any, .indoorSafe, .strangers,
                   ["Pick the drink and stick to it",
                    "Space them out or you will not sleep",
                    "One line of notes on each"]),

            POMake("food-market-lunch",
                   "Build lunch out of four small purchases at a market",
                   "One thing from four different stalls. No single dish, no plan. It is the most fun you can have with a small budget and a paper bag.",
                   .low, .couple, .gentle, .food, .any, .needsDry, .talking,
                   ["Cash and a bag",
                    "Four stalls, one item each — hold the rule",
                    "Find a bench for eating it"]),

            POMake("food-bread-bake",
                   "Bake bread and eat the first slice hot",
                   "A whole day of intermittent attention and about ninety seconds of genuine glory. The flat smells right for the rest of the evening, which is half the reward.",
                   .free, .fullDay, .gentle, .food, .winter, .indoorSafe, .solitary,
                   ["Flour, yeast and salt in the house",
                    "A tin or a tray, and a clean tea towel",
                    "Clear the afternoon around the proving times",
                    "Butter, for the hot slice"]),

            POMake("food-restaurant-window",
                   "Take the window table and watch the street",
                   "Ask for the window. Order slowly. Half the meal is the street outside and the other half is not being in any hurry. Two hours minimum.",
                   .moderate, .couple, .restful, .food, .any, .indoorSafe, .strangers,
                   ["Ring and ask for a window table",
                    "Book early evening for the best street traffic",
                    "Order in two waves rather than all at once"]),

            POMake("food-ice-cream-walk",
                   "Get an ice cream and walk until it is finished",
                   "Small, cheap, and complete. Buy it, then walk in whichever direction looks best, and turn round when the cone is gone. Half an hour, entirely uncomplicated.",
                   .low, .half, .gentle, .food, .summer, .needsSun, .strangers,
                   ["Find the good ice cream place, not the nearest",
                    "Napkins",
                    "Pick a direction before you order"]),

            POMake("food-fermentation",
                   "Start something fermenting on the kitchen counter",
                   "Sauerkraut, a jar of kimchi, a sourdough starter. Twenty minutes of work and then two weeks of checking on it, which turns one evening into a small ongoing relationship.",
                   .low, .couple, .gentle, .food, .autumn, .indoorSafe, .solitary,
                   ["Big jar, salt, and the vegetable",
                    "Read one reliable method through",
                    "Label the jar with the date",
                    "Somewhere out of direct sun to keep it"]),

            POMake("food-old-favourite",
                   "Go back to the restaurant you used to love",
                   "The one you stopped going to for no particular reason. Order what you always ordered. It will be exactly the same or completely different and both outcomes are interesting.",
                   .moderate, .couple, .gentle, .food, .any, .indoorSafe, .strangers,
                   ["Check it is still open and still takes bookings",
                    "Remember what you used to order",
                    "Go at the time of day you used to go"]),

            POMake("food-cocktail-one",
                   "Have one very good cocktail at a proper bar",
                   "One. At the bar, not a table. Made by someone who takes it seriously and is happy to explain what is in it. Then leave while it is still a good evening.",
                   .moderate, .couple, .gentle, .food, .any, .indoorSafe, .talking,
                   ["Find a bar with a real bartender, not a list",
                    "Sit at the bar",
                    "Decide before you go that it is one drink",
                    "Sort out how you get home"]),

            POMake("food-supper-club",
                   "Book a seat at a supper club or a shared table",
                   "Communal dining is built for people arriving one at a time. You will talk to whoever you are sat beside, or not, and either is entirely normal at that table.",
                   .moderate, .halfDay, .adventurous, .food, .any, .indoorSafe, .talking,
                   ["Book and check whether it is a shared table",
                    "Mention any dietary needs when booking",
                    "Arrive on time — these start together",
                    "Cash for the tip if it is not card"]),

            POMake("food-pantry-challenge",
                   "Cook dinner using only what is already in the house",
                   "No shopping, no substitutes bought. Whatever the cupboard yields becomes the menu. Constraint is the most reliable creative tool there is and this one is free.",
                   .free, .couple, .gentle, .food, .any, .indoorSafe, .solitary,
                   ["Empty the cupboard onto the counter first",
                    "No shop trips — the rule is the point",
                    "Write down whatever you invent"]),
        ]
    }

    // MARK: - Making

    static var making: [POIdea] {
        [
            POMake("make-pottery-class",
                   "Take a one-off pottery or ceramics class",
                   "Drop-in classes exist precisely for people who turn up alone. Two hours with your hands in clay, a teacher who will show you the same thing four times, and a wonky object at the end.",
                   .moderate, .halfDay, .gentle, .making, .any, .indoorSafe, .talking,
                   ["Book a taster or drop-in session",
                    "Wear clothes that can get ruined",
                    "Short nails, no rings",
                    "Ask when you can collect the fired piece"]),

            POMake("make-repair-thing",
                   "Fix something you have been meaning to fix",
                   "The wobbly chair, the button, the bike brake, the drawer that sticks. One item, one evening, one online guide. Enormously out of proportion to the effort.",
                   .low, .couple, .active, .making, .any, .indoorSafe, .solitary,
                   ["Pick the one item, not the list",
                    "Find the guide before you start dismantling",
                    "Lay parts out in the order they came off",
                    "Buy the one part you will need"]),

            POMake("make-zine",
                   "Make an eight-page zine out of one sheet of paper",
                   "Fold, cut once, and you have a booklet. Fill it with whatever you like — a guide to your street, a list, drawings. Finished in one evening, which is the point.",
                   .free, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["One sheet of A4 and a pen",
                    "Look up the one-cut fold beforehand",
                    "Decide the subject before you fold"]),

            POMake("make-photo-roll",
                   "Shoot one roll of film in one day and stop",
                   "Thirty-six frames, no deleting, no reviewing. Scarcity makes you look properly before you press. Get it developed and be surprised a week later.",
                   .moderate, .halfDay, .gentle, .making, .any, .needsDry, .solitary,
                   ["Buy or find a working film camera and a roll",
                    "Find a lab and check the price first",
                    "Thirty-six frames — do not save any"]),

            POMake("make-bread-board",
                   "Sand and oil a piece of wood into something useful",
                   "A board, a shelf, a stool leg. Sanding is the most meditative work there is, the smell is excellent, and at the end you own a thing you made.",
                   .low, .halfDay, .active, .making, .any, .indoorSafe, .solitary,
                   ["Sandpaper in three grades and food-safe oil",
                    "Work outside or over newspaper",
                    "Dust mask if you are sanding indoors",
                    "A cloth for the oiling"]),

            POMake("make-draw-100",
                   "Draw the same object one hundred times",
                   "A cup, a shoe, your own hand. The first ten are bad, the middle forty are boring, and somewhere after that your hand stops asking your brain for permission.",
                   .free, .halfDay, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Cheap paper, lots of it",
                    "One object, chosen and set on the table",
                    "Number each drawing in the corner"]),

            POMake("make-mixtape",
                   "Build a playlist with actual rules and a real ending",
                   "Not a mood folder. Fourteen tracks, a running order that matters, a beginning and a proper last song. Then listen to it all the way through as though someone gave it to you.",
                   .free, .couple, .restful, .making, .any, .indoorSafe, .solitary,
                   ["Decide the rule — a theme, a year, a key",
                    "Fourteen tracks maximum",
                    "Give it a name that is not the theme"]),

            POMake("make-mend-visible",
                   "Mend a piece of clothing so the mend shows",
                   "Contrast thread, deliberate stitching, no attempt to hide it. A visible repair turns damage into a decision and the garment gets more interesting rather than less.",
                   .low, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Needle, and thread in a color that shows",
                    "Pick the garment, ideally one you wear",
                    "Look up one stitch and practice it on a rag"]),

            POMake("make-terrarium",
                   "Build something small and green in a jar",
                   "Gravel, charcoal, soil, moss, one small plant. An hour of fiddly work and then a tiny landscape on your windowsill that basically looks after itself.",
                   .low, .couple, .gentle, .making, .spring, .indoorSafe, .solitary,
                   ["A clear jar with a lid",
                    "Gravel, charcoal, compost, moss",
                    "Newspaper down before you start",
                    "Long tweezers or a chopstick"]),

            POMake("make-write-1000",
                   "Write a thousand words about one hour of your life",
                   "Not a diary entry. A proper description of one specific hour — where you were, the light, what people said. Nobody has to read it and that is exactly why it can be honest.",
                   .free, .couple, .restful, .making, .any, .indoorSafe, .solitary,
                   ["Choose the hour before you start writing",
                    "Set a word target, not a time limit",
                    "No editing until you hit the number"]),

            POMake("make-print-block",
                   "Carve a stamp and print it on everything",
                   "A rubber block, a cutting tool, an evening. Print it on cards, on the inside of books, on a tote bag. Making a mark that repeats is unreasonably satisfying.",
                   .low, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Carving block, lino tool and ink pad",
                    "Sketch the design on paper first",
                    "Cut away from your fingers, always",
                    "Paper and a bag to print on"]),

            POMake("make-instrument-hour",
                   "Learn one whole song on an instrument",
                   "One song, start to finish, however badly. Not scales, not theory, not a practice regime. A whole song you can play at the end of the evening.",
                   .free, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Pick the song before you pick up the instrument",
                    "Find chords or tab you trust",
                    "Play it through badly, then again"]),

            POMake("make-bike-service",
                   "Strip, clean and re-oil your bicycle",
                   "Chain off, degreaser, brushes, an hour of getting filthy. The bike will run silently afterwards and you will understand a machine you use every week.",
                   .low, .couple, .active, .making, .spring, .indoorSafe, .solitary,
                   ["Degreaser, brushes, rags and chain oil",
                    "Work outside or on plenty of newspaper",
                    "Gloves, unless you like black hands",
                    "Watch one guide the whole way through first"]),

            POMake("make-model-kit",
                   "Build a model kit on a cleared table",
                   "Plane, ship, robot, house. Instructions, small parts, hours passing without you noticing. The most reliable way to disappear into an evening that exists.",
                   .moderate, .halfDay, .restful, .making, .winter, .indoorSafe, .solitary,
                   ["Buy the kit and check what glue it needs",
                    "Clear a table and get good light",
                    "A tray or a lid so parts cannot roll away"]),

            POMake("make-recipe-own",
                   "Invent a recipe and write it down properly",
                   "Cook something without a recipe, then write it up as though a stranger will make it — quantities, times, the bit that goes wrong. That write-up is the real work.",
                   .low, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Measure as you go, even roughly",
                    "Card or a notebook for the final version",
                    "Name it something ridiculous"]),

            POMake("make-candle-dye",
                   "Make something with your hands from a kit",
                   "Candles, soap, dyeing a shirt, block-printed cloth. Kits are not cheating — they remove the shopping and leave the doing, which is the part you wanted.",
                   .moderate, .couple, .gentle, .making, .any, .indoorSafe, .solitary,
                   ["Buy the kit and read it before starting",
                    "Cover every surface you care about",
                    "Ventilate the room if there are fumes",
                    "Set aside somewhere for it to cure"]),

            POMake("make-family-tree",
                   "Spend an evening on one branch of your family tree",
                   "Census records and free archives go a surprising distance. One branch, one evening. You will find one person whose life makes you sit back in the chair.",
                   .free, .couple, .restful, .making, .any, .indoorSafe, .solitary,
                   ["Write down what you already know first",
                    "Pick ONE branch and stay on it",
                    "Note your sources as you go"]),

            POMake("make-shelf-build",
                   "Build one piece of furniture, badly and on purpose",
                   "A shelf, a box, a plant stand. Timber cut to size at the shop, screws, an afternoon. It will be slightly out of square and you will like it more than the shop-bought one.",
                   .moderate, .halfDay, .active, .making, .any, .indoorSafe, .talking,
                   ["Measure the space and write the cut list",
                    "Ask the timber shop to cut to size",
                    "Screws, drill, and a spirit level",
                    "Clear the floor space to assemble on"]),
        ]
    }

    // MARK: - Moving

    static var moving: [POIdea] {
        [
            POMake("move-long-walk",
                   "Walk somewhere you would normally get a train to",
                   "Pick a destination two or three hours out on foot and walk the whole way. The point at which the familiar runs out and the unfamiliar begins is the best part of the day.",
                   .free, .halfDay, .active, .moving, .any, .needsDry, .strangers,
                   ["Plan the route and the way back",
                    "Broken-in shoes only",
                    "Water, snacks and a charged phone",
                    "Tell someone the route"]),

            POMake("move-swim-early",
                   "Do the first session of the day at the pool",
                   "Six thirty in the morning, four other people, water like glass. Nobody talks at that hour and everyone is quietly pleased with themselves. Cheapest slot too.",
                   .low, .couple, .active, .moving, .any, .indoorSafe, .strangers,
                   ["Check the early swim timetable",
                    "Bag packed the night before",
                    "Something to eat immediately after"]),

            POMake("move-class-drop-in",
                   "Take a drop-in class in something you cannot do",
                   "Boxing, ballet, climbing, tango basics. Being the worst person in the room for an hour is excellent for you and absolutely nobody there minds.",
                   .moderate, .couple, .adventurous, .moving, .any, .indoorSafe, .talking,
                   ["Book a beginner or taster session",
                    "Ask what to wear when you book",
                    "Arrive ten minutes early to say you are new",
                    "Water bottle"]),

            POMake("move-stairs-city",
                   "Climb every set of public stairs in one area",
                   "Cities are full of them and nobody uses them on purpose. Map three or four flights, do them all in one go, and finish somewhere with a view.",
                   .free, .couple, .active, .moving, .any, .needsDry, .strangers,
                   ["Find the stairs on a map first",
                    "Plan a route between them",
                    "Water — this is harder than it sounds"]),

            POMake("move-cycle-loop",
                   "Ride a bike route you have never ridden",
                   "Not the commute. Find a marked cycle route or a canal path and do the whole loop. Two hours of moving through places at a speed that lets you actually see them.",
                   .free, .halfDay, .active, .moving, .spring, .needsDry, .solitary,
                   ["Check tires, brakes and lights beforehand",
                    "Route saved offline or on paper",
                    "Water, a pump and a spare tube",
                    "Helmet and a lock"]),

            POMake("move-stretch-hour",
                   "Give one full hour to stretching on the floor",
                   "Not a class, not a video you race through. An hour, a mat, one long position at a time. It is boring for eight minutes and then it is not boring at all.",
                   .free, .couple, .restful, .moving, .any, .indoorSafe, .solitary,
                   ["Mat or a folded blanket",
                    "Quiet music or nothing at all",
                    "Phone out of the room"]),

            POMake("move-run-new-route",
                   "Run a route you have never run, no watch",
                   "No pace, no distance, no data. Pick a direction you have not run in and go until you want to turn around. Running without measuring it is a different activity entirely.",
                   .free, .couple, .active, .moving, .any, .needsDry, .solitary,
                   ["Leave the watch at home deliberately",
                    "Rough loop in mind so you get back",
                    "Tell someone the direction"]),

            POMake("move-dance-kitchen",
                   "Dance badly in your kitchen for the length of one side",
                   "Curtains closed if you must, but honestly nobody can see. Twenty minutes of moving to loud music is the cheapest mood change available and it requires no equipment.",
                   .free, .half, .active, .moving, .any, .indoorSafe, .solitary,
                   ["Queue up three songs that always work",
                    "Clear enough floor to move",
                    "Socks off — you will slide"]),

            POMake("move-hike-proper",
                   "Do a proper hike with a summit and a sandwich",
                   "A full day out, a route card, a real hill. The sandwich at the top of a hill you have walked up tastes like nothing else and the day empties your head completely.",
                   .low, .fullDay, .adventurous, .moving, .summer, .needsDry, .solitary,
                   ["Route, map and forecast checked the night before",
                    "Boots, waterproof, warm layer",
                    "Two liters of water and real food",
                    "Tell someone your route and return time"]),

            POMake("move-skate-rink",
                   "Go to a skating rink and hold the rail",
                   "Ice or roller, does not matter. Everyone there is falling over and the average skill level is far lower than you fear. An hour of concentrating on staying upright is a very effective holiday from thinking.",
                   .moderate, .couple, .active, .moving, .winter, .indoorSafe, .strangers,
                   ["Check session times and skate hire",
                    "Gloves and thick socks",
                    "Go at a quiet weekday session"]),

            POMake("move-yoga-park",
                   "Do a workout outdoors where anyone can see",
                   "A park, a beach, a quiet square. It feels mortifying for exactly ninety seconds and then it feels excellent. Nobody is watching, and the two who are do not care.",
                   .free, .couple, .active, .moving, .summer, .needsSun, .strangers,
                   ["Mat or towel",
                    "Find a flat patch away from paths",
                    "Water and sun protection"]),

            POMake("move-walk-night",
                   "Walk a familiar route after dark",
                   "The same streets you know completely, at ten at night, with the shops shut and the lighting doing all the work. Same route, completely different place.",
                   .free, .couple, .gentle, .moving, .autumn, .needsDry, .strangers,
                   ["Pick a route you know is well lit",
                    "Charged phone and a way home",
                    "Tell someone if it is a long one"]),

            POMake("move-climb-wall",
                   "Book an induction at a climbing wall",
                   "Bouldering walls are full of people concentrating too hard to notice you. An induction, an hour of falling onto mats, and forearms that ache for two days.",
                   .moderate, .couple, .adventurous, .moving, .any, .indoorSafe, .talking,
                   ["Book the beginner induction",
                    "Shoe hire — check whether socks are needed",
                    "Trim your nails",
                    "Water and something to eat after"]),

            POMake("move-tennis-wall",
                   "Hit a ball against a wall for an hour",
                   "Tennis, squash, football, whatever. There is a practice wall in most parks and it asks nothing of you except rhythm. Deeply repetitive and enormously calming.",
                   .free, .couple, .active, .moving, .summer, .needsDry, .solitary,
                   ["Find a practice wall or a quiet gable end",
                    "Ball and racket, plus a spare ball",
                    "Go when the courts are quiet"]),

            POMake("move-walk-alphabet",
                   "Walk to a street for every letter you can manage",
                   "Start at A and work through the map. It will take you down streets you have never had a reason to enter and you will give up around Q, which is fine.",
                   .free, .halfDay, .active, .moving, .any, .needsDry, .strangers,
                   ["Map app or a street index",
                    "Photograph each street sign as proof",
                    "Set a stopping rule before you start"]),

            POMake("move-ski-day",
                   "Buy a day pass for something with equipment hire",
                   "Skiing, snowboarding, a dry slope, an indoor snow center. Expensive, physical, and completely absorbing — the whole day exists only in the next thirty seconds.",
                   .splurge, .fullDay, .adventurous, .moving, .winter, .needsCold, .talking,
                   ["Book the pass and the hire together",
                    "Gloves, goggles and layers",
                    "Book a lesson if you have never been",
                    "Food plan — mountain food is expensive"]),

            POMake("move-walk-water",
                   "Walk from one bridge to the next and cross back",
                   "Any river, any two bridges. Down one bank, over, back up the other. A loop with a guaranteed view and a natural end point, which is all a walk needs.",
                   .free, .couple, .gentle, .moving, .any, .needsDry, .strangers,
                   ["Find two bridges with a walkable bank between",
                    "Check the path is continuous",
                    "Go near sunset if the light is good"]),

            POMake("move-swim-lake",
                   "Swim a length of somewhere with no lanes painted on it",
                   "A supervised lake, a designated wild swim spot, a sea pool. One length of open water, at whatever pace, with a horizon instead of a tiled wall.",
                   .low, .couple, .adventurous, .moving, .summer, .needsSun, .strangers,
                   ["Only supervised or recognized swim spots",
                    "Bright cap and a tow float",
                    "Never swim alone in open water",
                    "Dry clothes and a hot drink for after"]),
        ]
    }
}
